In [1]:
# Import dependencies.
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [2]:
# Read in CSV file.
df = pd.read_csv("cleaned_data.csv")

In [5]:
df.head()

,Unnamed: 0,id,program,previous_college,ethnic_description,gender,hs_ged,hours_attended,hours_scheduled,attendance_percentage,gpa,default_status,years_between_education,age_at_grad
0,0,10579,0,0,3,1,2,480.75,600.0,0.8013,82.5,0,4.725627,23.107935
1,1,11118,1,1,2,1,2,150.00,150.0,1.0000,95.0,0,11.625153,29.996509
2,2,10644,0,1,7,1,2,565.00,600.0,0.9417,90.5,0,34.494890,52.565077
3,3,10560,0,1,7,1,2,523.50,600.0,0.8725,81.0,0,2.486020,20.219443
4,4,10509,1,1,3,1,2,142.75,150.0,0.9517,85.0,0,10.973531,29.555706

In [4]:
# define dataset
X, y = df(n_samples=411, n_features=14, n_informative=5, n_redundant=5, random_state=1)
# define the model
model = LogisticRegression()
# fit the model
model.fit(X, y)
# get importance
importance = model.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))
# plot feature importance
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

TypeError: 'DataFrame' object is not callable